
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkyejooocx8oyxsl/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R business_areas $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R inquiry $DEPLOYPATH
    - /bin/cp -R interview $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
    - /bin/cp -R promotion $DEPLOYPATH
    - /bin/cp -R ERP_admin $DEPLOYPATH